### ISSUE TITLE
When data is large, Powa takes up CPU of memory

### ISSUE THREAD

**Issue by walnut-tom** [powa-team/powa#100]
When data is large, Powa takes up CPU of memory

**Comment by rjuju** [comment]
Hello,

I'm sorry but I'm not sure I understand your issue.  Could you elaborate a little more, and/or show some metrics about consumption?

**Comment by walnut-tom** [comment]
client use jdbc prepared statment, pg schema more than 10 thousand, Perform SQL more than 20 thousand per minute. The database server is out of memory. Restore normal after deleting Powa database.

**Comment by rjuju** [comment]
With this few details, it's hard to be really sure, but the latest release (v3.1.1) fix 2 bugs that have similar symptoms.

Can you try with last version and tell me if the problem is fixed?
