### ISSUE TITLE
powa not working when installing from official repo (postgres11+96)

### ISSUE THREAD

**Issue by guruguruguru** [powa-team/powa#112]
Hey, right now we are testing postgres11 and powa is now working correctly when installed from the official postgres repos on centos/redhat.

We get the following error when trying to log in:

`Unable to connect: powa-archivist version 3.2.X does not match powa-web version 3.1.X
`

If we just change the version in the init.py file it works but I am not sure if this would be the best way.

**Comment by rjuju** [comment]
Hi.

I just checked and it seems that powa-web is in version 3.2.0 for pg11 on centos/rhel: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/

Did you also upgrade the powa_11_web package?  If yes, did you restart the service?

**Comment by guruguruguru** [comment]
Hey rjuju,

`root@qp-pgtest01-a:~# rpm -qa |grep powa
powa_11-3.2.0-1.rhel7.x86_64
powa_11-web-3.2.0-1.rhel7.x86_64`

This i a fresh install so something seems to be wrong within the rpm.

Regards,
Dennis

**Comment by rjuju** [comment]
Ok.  I just checked and the rpm for 3.2.0 indeed contains v3.1.4.  Apparently the `powawebversion` wasn't updated: https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/powa/master/powa.spec;h=7f4785567d525a0775c650531adb285d55a9d1be;hb=HEAD#l14

@devrimgunduz are you watching here or should I open an issue on the rpm redmine?

**Comment by devrimgunduz** [comment]
Hi,

Sorry for the inconvenience. Just updated powa-web to 3.2.0. The packages will appear in 1 hour.

Regards, Devrim

**Comment by guruguruguru** [comment]
Thanks a Lot!

**Comment by rjuju** [comment]
Thanks a lot!

**Comment by guruguruguru** [comment]
@rjuju @devrimgunduz Sorry for bothering you again: I have just seen this error on a postgres 9.6 again, is it possible that the problem is also in the 96 packages?

`rpm -qa |grep powa
powa_96-3.2.0-2.rhel7.x86_64
powa_96-web-3.2.0-2.rhel7.x86_64
`

**Comment by rjuju** [comment]
@guruguruguru is the problem solved now?

For the archives sake, what was the error message before updating the extension?

**Comment by guruguruguru** [comment]
Yes sorry the Problem is solved. Error message was the same as above so i did an
>Alter extension powa update;
which fixed it.
