### ISSUE TITLE
Detect match random_page_cost for SSD storage

### ISSUE THREAD

**Issue by guettli** [powa-team/powa#114]
If you are running PG on SSD storage, then you should lower random_page_cost.

See: https://dba.stackexchange.com/questions/204178/autodetect-random-page-cost-vs-seq-page-cost

Can powa detect and report this?

**Comment by frost242** [comment]
Hello,
This is out of the scope of PoWA. You should probably submit your question to the postgresqltuner project (https://github.com/jfcoz/postgresqltuner).
Regards

**Comment by guettli** [comment]
Thank you for your fast reply. The postgresqltuner script looks good.
