### ISSUE TITLE
function powa_take_snapshot() does not exist at character 8

### ISSUE THREAD

**Issue by kel00s** [powa-team/powa#115]
Hi all,

After adding powa to shared_libraries I spotted below issue. Can you help me with finding root cause?

Regards,

```
2019-04-05 12:54:11.875 UTC @ 8101  LOG:  POWA connected to database powa
2019-04-05 12:54:11.876 UTC @ 8101  ERROR:  function powa_take_snapshot() does not exist at character 8
2019-04-05 12:54:11.876 UTC @ 8101  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-04-05 12:54:11.876 UTC @ 8101  QUERY:  SELECT powa_take_snapshot()
2019-04-05 12:54:11.877 UTC @ 1986  LOG:  worker process: powa (PID 8101) exited with exit code 1
```

**Comment by rjuju** [comment]
Did you install powa on the powa database?

What does this query returns, on the powa database:

SELECT pronamespace::regnamespace, oid::regprocedure FROM pg_proc WHERE proname = 'powa_take_snapshot';

**Comment by kel00s** [comment]
Sorry for long response:

```
 pronamespace |         oid
--------------+----------------------
 public       | powa_take_snapshot()
(1 row)
```

**Comment by rjuju** [comment]
Is it on the `powa` database?, on the local server?

**Comment by kel00s** [comment]
yes,

**Comment by rjuju** [comment]
I see.  Did you modify the search_path setting, either globally or for the user and/or database?

**Comment by kel00s** [comment]
Here is the value,

```
    name     |     setting
-------------+-----------------
 search_path | "$user", public
(1 row)
```

**Comment by rjuju** [comment]
Is it the output from pg_settings ? What does `\drds` show?

**Comment by kel00s** [comment]
Yes, It was from pg_settings

```
powa=# \drds
                             List of settings
       Role        | Database |                 Settings
-------------------+----------+-------------------------------------------
 postgres_exporter |          | search_path=postgres_exporter, pg_catalog
(1 row)
```

**Comment by rjuju** [comment]
Is `postgres_exporter` your bootstrap superuser?

**Comment by kel00s** [comment]
Sorry for long response, I had to drop implementing powa project into our infra cause we need to have installed this as sidecar to primary and standby servers.

Please close.

Many thanks for help!

**Comment by rjuju** [comment]
I'm not sure that I get your last comment.  Is your main issue with powa the fact that you can't use it to track activity on a standby server?

**Comment by rjuju** [comment]
I'm closing this issue.  If you needed a tool working on a standby, please note that the v4 (released in beta today) is able to do that!
