### ISSUE TITLE
Release the obvious demo database

### ISSUE THREAD

**Issue by frost242** [powa-team/powa#116]
Hello,
Maybe it would be useful to release the demo db "obvious" as it would permit to demonstrate easily the usefulness of PoWA while the demo site is down.
Thanks

**Comment by rjuju** [comment]
Indeed, that's a very good idea.  We should also publish the tpc database, and the pgbench scenarios for both.

**Comment by frost242** [comment]
Good idea. The tpc database may need some work also as it is a little erstarz of a real TPC-something database.

**Comment by rjuju** [comment]
I just pushed all of that in the new https://github.com/powa-team/powa_demo repo!
