### ISSUE TITLE
(RPM-)Packaging for powa dependencies (PG12)

### ISSUE THREAD

**Issue by guruguruguru** [powa-team/powa#124]
Hey there,

right now if we try to install powa_12 on CentOS7 from the official postgres repo there are two missing dependencies (pg_qualstats12 and pg_stat_kcache12). Is this a known issue? Are there plans to release the packages in the near future?

Thanks a lot,
Dennis

**Comment by devrimgunduz** [comment]
@rjuju looks like an oversight :( Sorry about that. Fixed.

**Comment by guruguruguru** [comment]
Thanks all!

**Comment by rjuju** [comment]
Thanks a lot!
