### ISSUE TITLE
Where should I enable extensions?

### ISSUE THREAD

**Issue by sanpii** [powa-team/powa#127]
Hello,

I’m a little confusing which extensions I should enable only for the `powa` database and which for all databases?

**Comment by rjuju** [comment]
Hello,

The only extension that may be installed on all databases is hypopg, and only if you want to have automatic index suggestion validation.  All other extensions (the stats extensions as described at https://powa.readthedocs.io/en/latest/components/stats_extensions/index.html) should only be created in the powa database.

If you use the remote mode, that's the same but the stats extensions should be created on both the repository powa database and each remote server, on the powa database.

**Comment by sanpii** [comment]
Fine, thank you!
