### ISSUE TITLE
hypopg query problem

### ISSUE THREAD

**Issue by seqizz** [powa-team/powa#134]
Hi there,

Not sure if I should open this here or powa-web, but looks like hypopg integration has some issues on the `predicates` tab of it:

```
Could not create hypothetical index: function hypopg_create_index(unknown) does not exist
```

On the database itself, I can see the error in the postgresql logs:
```
2020-06-17 08:59:09 UTC [21007-1] powa@ipaddr ERROR:  function hypopg_create_index(unknown) does not exist at character 24
2020-06-17 08:59:09 UTC [21007-2] powa@ipaddr HINT:  No function matches the given name and argument types. You might need to add exp
licit type casts.
2020-06-17 08:59:09 UTC [21007-3] powa@ipaddr STATEMENT:  SELECT indexname
        FROM hypopg_create_index('CREATE INDEX ON "public"."my_table"(param_id,type)')
```

Weird thing is, when I give the same query manually, it returns a value.

Environment:
- Debian 10 (Buster)
- hypopg version 1.1.3-1.pgdg100+1
- postgresql version 11.8-1.pgdg100+1
- powa version 4.0.1-1.pgdg100+1

> Thank you for this tool!

**Comment by rjuju** [comment]
Hello,

Either repository is ok!

That's indeed strange.  Was the query manually run on the same server and the same database, with the same user?

**Comment by seqizz** [comment]
> with the same user?

This is the part I facepalm.. Switching to powa role shows that user does not have the rights to execute the function.

Sorry for the noise and thanks for the tip!
