### ISSUE TITLE
Issue on wget installation

### ISSUE THREAD

**Issue by GowthamvelP** [powa-team/powa#135]
Downloaded source from the below URL.
wget https://github.com/dalibo/powa/archive/REL_1_2_1.zip

On running make in the directory where the source file is located, I'm getting the below error.

```
powa.c:95:12: error: no member named 'bgw_main' in 'struct BackgroundWorker'
    worker.bgw_main = powa_main;
    ~~~~~~ ^
powa.c:193:39: error: too few arguments to function call, expected 4, have 3
                          time_to_wait);

/usr/local/Cellar/postgresql/10.1/include/server/storage/latch.h:174:2: note: 'WaitLatch' declared here
 extern int WaitLatch(volatile Latch *latch, int wakeEvents, long timeout,
 ^
2 errors generated.
make: *** [powa.o] Error 1

```
Getting the error in the latest released version as well.  powa-REL_1_2_2

Postgresql version - PostgreSQL 10.1 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.38), 64-bit

Please help.

**Comment by rjuju** [comment]
Hello,

The repository has moved a very long time ago, as mentioned in the README of the master branch in this repository at https://github.com/powa-team/powa:

> Where's the code ?
> This repository contains the PoWA documentation. The source code is split in multiple separate projects:
> 
> PoWA-archivist: the statistic collector

Please use the up to date code at https://github.com/powa-team/powa-archivist, which is version 4.0.1 (see https://github.com/powa-team/powa-archivist/releases).
