### ISSUE TITLE
invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by edjiesa** [powa-team/powa#136]
SERVER LAB 27: Error while calling powa_qualstats_src: invalid byte sequence for encoding "UTF8": 0xac CONTEXT: PL/pgSQL function powa_qualstats_src(integer) line 85 at RETURN QUERY

can you help me? am use enterprisedb

**Comment by rjuju** [comment]
Hello,

Are you using local mode or remote mode?  Can you also specify the exact version of powa and pg_qualstats?

Could you also provide the full error message (with the underlying statements).

**Comment by rjuju** [comment]
I'm closing this issue as I have no news for some months.  Feel free to reopen it if needed.
