### ISSUE TITLE
`permission denied for table powa_servers` at the first run

### ISSUE THREAD

**Issue by rostamiani** [powa-team/powa#139]
Hi
I installed POWA using the quick access doc. Now I can see the login page but when logged in with the correct powa user I see `500: Internal Server Error`!

And this happens in the server:
```sql
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
        cursor.execute(statement, parameters)
    ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table powa_servers
    
    [SQL: SELECT
           CASE WHEN id = 0 THEN
              '<local>'
           ELSE
              COALESCE(alias, hostname || ':' || port)
           END AS alias,
            error
            FROM powa_servers s
            JOIN (SELECT srvid, unnest(errors) error
                FROM powa_snapshot_metas
                WHERE errors IS NOT NULL
            ) m ON m.srvid = s.id]
    (Background on this error at: http://sqlalche.me/e/13/f405)
```

Is there any log available?
Witch permision is needed? I granted `powa` user to the `powa` dataabse

**Comment by rjuju** [comment]
Hello!

As this is using a standard postgres connection, all logs should be available with the rest of the postgres logs.

All permission requirements are documented at https://powa.readthedocs.io/en/latest/security.html.  Can you check and let us know if we missed any privilege?
