### ISSUE TITLE
idea: be able to merge data from several instances

### ISSUE THREAD

**Issue by marco44** [powa-team/powa#141]
That's just something that crossed my mind today because we would have a use case… to be able to consider that several replicas are one logical instance in the interface. I didn't see an issue about this, so let's write this down.

We'd like to have a view of all queries running on a "logical instance", as we have a lot of read queries going to secondary servers. The system indicators would probably have no meaning in this mode, I don't know.

Thoughts ?

**Comment by rjuju** [comment]
Sorry I forgot to reply on this one.

I think that not only the system indicators but also most of the metrics wouldn't make sense if we displayed activity from multiple servers: the hit ratio, average time and such would become kind of useless I think.

I'm wondering if we could find a better way to give the information that you need.  I'm assuming that what you want is for instance have an idea of how many tps a whole "logical instance" ( and maybe one of the underlying databases) is achieving more than some kind of averaged view of all the available information?  If the scope is narrow enough we could imagine a new set of pages that shows only a few graphs / charts for those logical instances, that would live outside the per (server, db, query) ones.

We would still need to find a way to configure those logical instances, obviously, which may be another problem as for now we don't really provide a way to configure powa through the UI.  Maybe it's time to work on that.

**Comment by marco44** [comment]
This seems not that important, as we've not done it yet :)
