### ISSUE TITLE
How can I move the remote powa server?

### ISSUE THREAD

**Issue by rostamiani** [powa-team/powa#144]
I have a remote POWA server that reached disk limits. How can i move POWA and it's logs to another server?
I Installed POWA in the new server but is it enough to copy the powa database?

**Comment by rjuju** [comment]
Hello,

The remote PoWA database is a standard database.  You can either do a pg_dump / pg_restore or turn off postgres, move the data on a new server and start postgres again (for the latter all the data will be moved, it can be a problem if you have multiple databases).  You'll have to reconfigure powa-collector and powa-web to connect to the new server if it's using a different IP address, but apart from that there shouldn't be any problem.

**Comment by rjuju** [comment]
Hello @rostamiani 

Could you move the powa database?
