### ISSUE TITLE
DROP queries are hanged if powa is enabled

### ISSUE THREAD

**Issue by anikin-aa** [powa-team/powa#166]

**Comment by rjuju** [comment]
hi,

could you provide more details? for instance, are you using the local mode
(with the bgworker) or the remote mode (with powa-collector), and ideally
the steps to reproduce your problem from scratch

**Comment by anikin-aa** [comment]
@rjuju , sorry my bad, i created two issues by accident, let's proceed in https://github.com/powa-team/powa/issues/167

**Comment by rjuju** [comment]
Ok.
