### ISSUE TITLE
powa related queries are visible under all databases

### ISSUE THREAD

**Issue by sajiljosephs** [powa-team/powa#172]
I could see powa queries listed under other databases which makes it difficult for optimisation. Is there an option to exclude powa queries under other databases ?

**Comment by rjuju** [comment]
Do you mean the query automatically run when browsing powa-web (for instance when looking as possible missing indexes and things like that), or that the queries that are run for the snapshot are also showed in other databases?

For the former, it's currently not possible to hide them, as there's nothing that distinguish them from other queries.  You can however set powa_servers.allow_ui_connection = false for the given server.  Some features will be missing in the UI but you shouldn't have powa-related queries on non-powa databases anymore.
