### ISSUE TITLE
Unable to connect: powa-archivist version 4.2.X does not match powa-web version 4.1.X

### ISSUE THREAD

**Issue by jcujhc** [powa-team/powa#180]
Hi,

First of all , thank you for great tool powa.
We are using it and also using powa web. After update Postgres and powa packages I got error on page.
Unable to connect: powa-archivist version 4.2.X does not match powa-web version 4.1.X

I checked packages , there is no available powa_13(or 14 15 16)-web-4.2 package to matches powa-archivist version 4.2

rpm -qa |grep powa
powa_13-4.2.2-1PGDG.rhel8.x86_64
powa-archivist_13-4.2.2-1PGDG.rhel7.x86_64
powa_13-web-4.1.4-1.rhel8.x86_64

we are using this repos:
https://download.postgresql.org/pub/repos/yum/13/redhat/ --->   (rhel-8.9-x86_64/)

I am looking for powa-archivist_13-4.1 or powa_13-web-4.2     :-)

Is there any way how to fix it ? (e.g. download and install powa_13-web newst package ? )

I also tried powa-web without version, but I can't run it
[root@XXX ~]# yum list | grep powa-web
powa-web.noarch                                                   4.2.0-1PGDG.rhel8                                                 @pgdg-common

[root@XXX ~]# /usr/bin/nohup /usr/bin/powa-web --config=/etc/powa-web_NONPROD_AWS_HTTPS.conf &
[1] 2079594
[root@XXX ~]# /usr/bin/nohup: ignoring input and appending output to 'nohup.out'

[1]+  Exit 1                  /usr/bin/nohup /usr/bin/powa-web --config=/etc/powa-web_NONPROD_AWS_HTTPS.conf
[root@ip-10-175-10-218 ~]# cat nohup.out
Traceback (most recent call last):
  File "/usr/bin/powa-web", line 4, in <module>
    from powa import make_app
ModuleNotFoundError: No module named 'powa'
Traceback (most recent call last):
  File "/usr/bin/powa-web", line 4, in <module>
    from powa import make_app
ModuleNotFoundError: No module named 'powa'
Traceback (most recent call last):
  File "/usr/bin/powa-web", line 4, in <module>
    from powa import make_app
ModuleNotFoundError: No module named 'powa'

[root@XXX ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

Thanks
Jozef Cuj
dba

**Comment by rjuju** [comment]
Hi,

Thanks a lot!

Unfortunately the RPM packages have been broken for a long time.  I already pinged the packager 8 months ago about that (https://github.com/powa-team/powa-web/issues/173#issuecomment-1801865089) but nothing changed since.  There is unfortunately nothing that I can do.  I can recommend debian/ubuntu as those packages are guaranteed to work, but that's probably not an option.  You could otherwise try to get powa-web from pypi, as this one is also guaranteed to work.  The last option would be to rely on the official container: https://hub.docker.com/r/powateam/powa-web  as it's also guaranteed to be up to date.

**Comment by jcujhc** [comment]
Hi,
Thanks you for quick respond.
I will try container at first, with pip (and python) I don't have experience.
Good luck with powa project and have a nice day
jc

**Comment by rjuju** [comment]
Thanks a lot!

Also note that for now not a lot of efforts have been put in the various containers to make them extensible and tunable, but I do want to make them one of the recommended (if not the first choice) for using powa.  So if you face any difficulty or problem with those feel free to open an issue either here or on the https://github.com/powa-team/powa-web or https://github.com/powa-team/powa-podman repository and I will be happy to improve those.
