### ISSUE TITLE
Typo in documents

### ISSUE THREAD

**Issue by tarkhil** [powa-team/powa#183]
In quickstart "pg_stat_statements,powa,pg_stat_kcache,pg_qualstats.pg_wait_sampling" instead of "pg_stat_statements,powa,pg_stat_kcache,pg_qualstats,pg_wait_sampling"

**Comment by rjuju** [comment]
Thanks a lot for the report!  Fixed in 2019dffc2ae2144ca0d5481cd07e60e07680de3a
