### ISSUE TITLE
QUERY

### ISSUE THREAD

**Issue by devopsproximaops** [powa-team/powa#186]
HI everyone, 
I have an error via loggin UI, 
<lambda>() missing 1 required positional argument: 'query'
Any solutions for it, i have install everything through the documentation

**Comment by rjuju** [comment]
hi,

which documentation page did you follow? we document multiple installation process.

also, can you precise which version of each tool you setup? we're in the middle of the releasing v5 so there might be inconsistencies here and there due to that as we only have a single version of the documentation.

**Comment by devopsproximaops** [comment]
hi, i have already fixed these, from one of the documents, but not remeber which one, with adding 
   'query': {'client_encoding': 'utf8'} 
   in powa-web.conf. 
   But now i have another issue which can be because of version,as i have used latest documentation
   
   
    HTTPServerRequest(protocol='http', host='95.47.238.222:8888', method='GET', uri='/server/0/metrics/database_all_queries/probilet/?from=2024-10-13+05%3A25%3A54%2B0500&to=2024-10-13+06%3A25%3A54%2B0500', version='HTTP/1.1', remote_ip='94.158.60.56')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
        self.dialect.do_execute(
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
        cursor.execute(statement, parameters)
    psycopg2.errors.UndefinedColumn: column psh.toplevel does not exist
    LINE 14:       SELECT psh.dbid, psh.toplevel, psh.userid, psh.queryid...
    
    VERSIONS:
hypopg 1.1.4
pg_qualstats 2.0.2
pg_stat_kcache 2.2.0
pg_stat_statements  1.8
pg_track_settings 2.0.1
pg_wait_sampling  1.1
powa  4.1.2


i think when installing pg_wait_sampling is not creating everything

**Comment by rjuju** [comment]
the top level information was added in powa-archivist 4.2 and you say you installed powa 4.1.x. 

you either have powa-web in 4.2.x (although there should be a warning or error) in that case, or you have different powa-archivist versions on different servers. unfortunately you didn't specify which version of powa-web you're using or how you installed the tool so I can't provide more details.

**Comment by rjuju** [comment]
the top level information was added in powa-archivist 4.2 and you say you installed powa 4.1.x. 

you either have powa-web in 4.2.x (although there should be a warning or error) in that case, or you have different powa-archivist versions on different servers. unfortunately you didn't specify which version of powa-web you're using or how you installed the tool so I can't provide more details.
