### ISSUE TITLE
Errors while creating powa extensions

### ISSUE THREAD

**Issue by hrawulwa** [powa-team/powa#188]
I'm getting errors on only couple of DB servers when creating extensions.
I have a remote setup, and no issues when creating extensions on hundreds of other servers.

CREATE EXTENSION pg_stat_kcache CASCADE;
ERROR:  no schema has been selected to create in
CREATE EXTENSION pg_qualstats CASCADE;
ERROR:  no schema has been selected to create in
CREATE EXTENSION pg_wait_sampling CASCADE;
ERROR:  no schema has been selected to create in
CREATE EXTENSION hypopg CASCADE;
ERROR:  no schema has been selected to create in
CREATE EXTENSION powa CASCADE;
CREATE EXTENSION

The script just logins to postgres database as postgres user and creates these extensions.
Any idea why it is complaining about the schema only in the few servers?

Thanks
Hari

**Comment by rjuju** [comment]
This is because for some reason on those few servers there is no default schema available.  It usually means either:
- you have a non default search_path that points to non existing schema (maybe they exist on other databases but not postgres)
- you have the default search_path (`"$user", public`) but public schema has been removed

In both cases you will end up with the error you see.  It probably works for the powa extension as in version 4.x it specifies the public schema, so the extension framework does create the extension schema if it doesn't exist (this changed in version 5 so you would have hit the same error).

**Comment by hrawulwa** [comment]
Yes, I do see that the search path was incorrectly set to a schema which is existing on database other than postgres, on these servers. I checked on rest of the servers where this is not an issue, the search path was set to (postgres, public).
How do I get around this issue, and still create the extensions as postgres user under postgres database?

Thanks
Hari

**Comment by rjuju** [comment]
I don't know what your requirements are, nor how the search_path was changed.  One way would be to change the default search_path for postgres database if this is where you install the extension, something like

```
ALTER DATABASE postgres SET search_path = 'public';
```

**Comment by hrawulwa** [comment]
I'm also not sure how search_path was changed. May be it was set by mistake. I will correct the search path for these issue servers, and create the extensions. Thanks for the advice.

I got another issue, which is again happening on only very few servers compared to hundreds of servers registered.
This issue is not related to extensions in this case, The extensions got created fine. However, Powa web UI is displaying errors as below:
Error while calling public.powa_kcache_src: This module can only be loaded via shared_preload_libraries CONTEXT: SQL statement "SELECT now(), k.queryid, k.top, k.userid, k.dbid, k.plan_reads, k.plan_writes, k.plan_user_time, k.plan_system_time, k.plan_minflts, k.plan_majflts, k.plan_nswaps, k.plan_msgsnds, k.plan_msgrcvs, k.plan_nsignals, k.plan_nvcsws, k.plan_nivcsws, k.exec_reads, k.exec_writes, k.exec_user_time, k.exec_system_time, k.exec_minflts, k.exec_majflts, k.exec_nswaps, k.exec_msgsnds, k.exec_msgrcvs, k.exec_nsignals, k.exec_nvcsws, k.exec_nivcsws FROM pg_stat_kcache() k JOIN pg_roles r ON r.oid = k.userid WHERE NOT (r.rolname = ANY (string_to_array( powa_get_guc('powa.ignored_users', ''), ','))) AND k.dbid NOT IN (SELECT oid FROM powa_databases WHERE dropped IS NOT NULL)" PL/pgSQL function powa_kcache_src(integer) line 14 at RETURN QUERY
Error while calling public.powa_wait_sampling_src: pg_wait_sampling shared memory wasn't initialized yet CONTEXT: SQL statement "SELECT now(), COALESCE(pgss.dbid, 0) AS dbid, s.event_type, s.event, s.queryid, sum(s.count) as count FROM pg_wait_sampling_profile s -- pg_wait_sampling doesn't offer a per (userid, dbid, queryid) view, -- only per pid, but pid can be reused for different databases or users -- so we cannot deduce db or user from it. However, queryid should be -- unique across differet databases, so we retrieve the dbid this way. -- Note that the same queryid can exists for multiple entries if -- multiple users execute the query, so it's critical to retrieve a -- single row from pg_stat_statements per (dbid, queryid) LEFT JOIN (SELECT DISTINCT s2.dbid, s2.queryid FROM pg_stat_statements(false) s2 ) pgss ON pgss.queryid = s.queryid WHERE s.event_type IS NOT NULL AND s.event IS NOT NULL AND COALESCE(pgss.dbid, 0) NOT IN (SELECT oid FROM powa_databases WHERE dropped IS NOT NULL) GROUP BY pgss.dbid, s.event_type, s.event, s.queryid" PL/pgSQL function powa_wait_sampling_src(integer) line 4 at RETURN QUERY

Thanks
Hari

**Comment by rjuju** [comment]
this is also an issue with your setup. for some reason at least pg_stat_kcache is not in shared_preload_libraries

**Comment by hrawulwa** [comment]
Thanks for correctly pointing it out. None of the powa extensions are present in shared_preload_libraries on these servers.

**Comment by hrawulwa** [comment]
Thanks for quick response
