### ISSUE TITLE
Powa and postgres read-only slave.

### ISSUE THREAD

**Issue by exordium-frozen** [powa-team/powa#38]
Hi.
My setup - postgresql master and slave (one at this time).
Powa gathering stats from master, writing stats to the powa database.
But most of read queries runs on slave, and I want to get stats about those queries too.

Any suggestions?

**Comment by mtrofimm** [comment]
would it be possible to define a different postgres cluster for powa to store data?

**Comment by rdunklau** [comment]
Its not possible at the moment, but at patch for such an addition would most definitely be welcome. Its not at the top of our priority list though...
