### ISSUE TITLE
Hit ratio for missing values

### ISSUE THREAD

**Issue by marco44** [powa-team/powa#59]
For a query, when it has not been run over a certain period of time, hit ratio is displayed as 0. It would be better to display it at 100% I think (meaning there was no problem during this period)

**Comment by rjuju** [comment]
Which version of powa-web are you using ?
I can't reproduce this behavior. If there hasn't been any block access for the query in the selected interval, "N/A" is displayed.

**Comment by marco44** [comment]
It happens if you have access on this query during the time interval, but not for the whole range.

Try it with a query that is run 3 times a day…

**Comment by rjuju** [comment]
Moved to https://github.com/powa-team/powa-web/issues/63
