### ISSUE TITLE
Keep dropped databases

### ISSUE THREAD

**Issue by marco44** [powa-team/powa#63]
Currently, when a database is dropped, we lose its data in the GUI: everything is stored with the dbid.

We should have a powa_pg_database_history to keep track of all seen databases:
- keep last name (and dbid obviously) of deleted databases
- apply renames if databases are renamed

**Comment by rjuju** [comment]
We should also explicitly show on the UI that the database has been dropped. Would you like to keep track of when approximatively the database has been dropped, of the end of any activity is enough?

Also, obvisouly a lot of features won't work, like doing explain of related queries, but there's nothing we can do about it.

**Comment by marco44** [comment]
End of activity is enough, I think.  But storing the date when the database has been dropped in a table wont kill performance :)

**Comment by rjuju** [comment]
Some preliminary work has been done : 

- https://github.com/dalibo/powa-archivist/commit/b10bfe92b79ae00e11c65c7964b43fe45599afea
- https://github.com/dalibo/powa-web/commit/2bf1ce3eab9f6e9adb85a50be3590d8185d5a126

Some work is still needed for some corner cases, like if a database is renamed and a snapshot didn't occur for instance.

**Comment by rjuju** [comment]
The limitations I was mentioning are probably not critical, and we already keep track of deleted and renamed database.  I'm closing this issue.  If you think more could be done, please open a new issue in powa-archivist project!
