### ISSUE TITLE
only SELECT statements

### ISSUE THREAD

**Issue by Olivier59** [powa-team/powa#72]
I installed powa with stats extensions (pg_stat_statements, pg_qualstats, pg_stat_kcache).
Versions are : 
powa : 3.0.0
pg_stat_statements : 1.3
pg_stat_kcache : 2.0.2
pg_qualstats : 0.0.9

I did a benchmark with pgbench. 
Currently when I check details in PoWA-web for queries on pgbench database, I see only SELECT statements.
In pg_stat_statements view (psql console), I can find other statements (insert, ...) but not in PoWA-web.

I checked documentation but anything related.
Do you have any advice or tips to give?

Regards

**Comment by rjuju** [comment]
Did you check that the non SELECT statements are in the same database you're looking at, and were executed in the interval you selected (by default last hour)?

You can check with the following query on the powa database for instance:
```sql
SELECT DISTINCT datname,pgss.queryid AS pgss_queryid,ps.queryid AS ps_queryid,pshc.queryid AS pshc_queryid, pgss.query
FROM pg_stat_statements pgss
JOIN pg_database d on d.oid = pgss.dbid
LEFT JOIN powa_statements ps using (userid,dbid,queryid)
LEFT JOIN powa_statements_history_current pshc using (userid,dbid,queryid)
WHERE pgss.query ILIKE '%insert%';
```

**Comment by Olivier59** [comment]
Thanks for your answer.
Did a new pgbench (drop pgbench and reinit).

Your query :
![image](https://cloud.githubusercontent.com/assets/18262980/14323797/56e1dd66-fc22-11e5-9a08-beeede529adc.png)

20 minutes after pgbench execution, I can see in powa-web :
![image](https://cloud.githubusercontent.com/assets/18262980/14323772/2b258506-fc22-11e5-8cbf-83d5e2f1d94e.png)

In attachment, content of pg_stat_statement on pgbench database.
[pg_stat_statements.txt](https://github.com/dalibo/powa/files/206856/pg_stat_statements.txt)

**Comment by rjuju** [comment]
I'll try to reproduce this issue.

Can you specify the pgbench command, and the powa parameters (frequency and colaesce at least)?

**Comment by Olivier59** [comment]
Installation as explained in http://powa.readthedocs.io/en/latest/

postgres=# show server_version;
 server_version
----------------
 9.5.1
(1 ligne)

postgres=# show powa.frequency;
 powa.frequency
----------------
 5min
(1 ligne)

postgres=# show powa.retention;
 powa.retention
----------------
 1d
(1 ligne)

postgres=# show powa.database;
 powa.database
---------------
 powa
(1 ligne)

postgres=# show powa.coalesce;
 powa.coalesce
---------------
 100
(1 ligne)


Commands used to run pgbench :

$ pgbench --version
pgbench (PostgreSQL) 9.5.2

dropdb --port=5431 pgbench
createdb --port=5431 pgbench
pgbench --port=5431 -i pgbench -s 50

pgbench --port=5431 -c 10 -t 100 pgbench
or
pgbench --port=5431 -c 10 -t 1000 pgbench
or
pgbench --port=5431 -j 2 -c 10 -t 1000 pgbench

**Comment by rjuju** [comment]
Thanks.

So the issue happens when a query, or a set of queries, are only run during one snapshot interval (5 min by default). In this case, these queries are totally ignored by the UI.  These queries are probably not the most critical, but it's still bad.

I'll work on a patch to fix this, thank a lot for the test case!

**Comment by rjuju** [comment]
This is a powa-web issue, so I'll create an issue there, and link this issue for reference
