### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by frost242** [powa-team/powa#87]
Here are some items to add/improve in the current documentation : 

- [ ] document the architecture PoWA with a schema
- [ ] tell about current limits: no stats recording on a standby server
- [ ] tell about all metrics that PoWA provides

**Comment by rjuju** [comment]
All of this should be done with modifications for v4.  @anayrat was kind enough to work on architecture graphs for the article describing the new version, I'll incoporate them to the documentation soon.
