### ISSUE TITLE
can not log in by web

### ISSUE THREAD

**Issue by lissali** [powa-team/powa#94]
Hi,
I install powa successfully by guide. 
And create role powa with password 'postgres' under superuser 'postgres'
After powa-web starting, I tried to log in by 'postgres/postgres', but failed

**Comment by rjuju** [comment]
Hello,

I'm not sure I'm following your setup. Did you create a "powa" role with "postgres" password, or do you try to connect with default "postgres" superuser ?

Can you provide logs from server and your pg_hba.conf? It should say why the connection is refused.

**Comment by rjuju** [comment]
Hello,

any update on this issue?
