### ISSUE TITLE
creation extension powa in a different schema

### ISSUE THREAD

**Issue by shalat31** [powa-team/powa#99]
Hello ,
I'm trying to install powa in a specific application context: the schema public is deleted .
When i perform the command :
create extension powa with schema "name_schema" , this message is generated 'ERROR: extension "powa" must be installed in schema "public"'.
Why this option is not allowed ?
This correction may be possible in a future version ?
Thank you 
Best regards
Sylvie Halat

**Comment by rjuju** [comment]
Hello,

Yes for now the schema is fixed.  We strongly recommend to install the powa extension in a dedicated database, so forcing the public schema shouldn't be an issue, and it helps keeping the code simple.  Do you use a dedicated database, and if yes do you have strong requirements about not having a public schema?

**Comment by shalat31** [comment]
Thank you for your reply.
Yes we use a dedicated database , these are recommendations to respect in the enterprise .Specific schema are created for our databases

**Comment by rjuju** [comment]
Ok.  I'll try to implement that, but it'll take some time since allowing different schema also means allowing to change the schema at any time, so I need to make sure it doesn't introduce any regression in every cases.

**Comment by shalat31** [comment]
Thank you ! It's a good news .

**Comment by rjuju** [comment]
Sorry for the super long answer.  We ended up rewriting most of powa to allow storing the data in a different server.  This will solve many existing problems (it now works on a standby, no more overhead on your servers...), and since this different server should ideally be dedicated for powa and not used for other application, I hope that this also address your problem.

**Comment by shalat31** [comment]
Thank you ,
I will test the lastest version and will you inform about result.
Best regards

**Comment by Kamal-Villupuram** [comment]
Hi,

I tried to install powa on different schema but it failed saying it can be installed only on public schema. I am using powa-4.1.2.

**Comment by rjuju** [comment]
Yes, as I mentioned in my previous comment you can now have a dedicated server to store data from many remote servers.  The only need for the powa extension on remote servers is only to provide the needed wrappers for the various data sources.  It should leverage most of the concerns about the public schema as the repository server should be a dedicated server, and the remote servers won't store any data for powa.
